channels:
  - anaconda
  - nodefaults
dependencies:
  - python=3
  - matplotlib
  - conda-forge::opencv>=4.1.0
  - numpy
  - pandas
  - scikit-learn
  - labelme
# - scipy
  - conda-forge::imantics
  - pip
  - pip:
    - http://download.agisoft.com/Metashape-1.5.5-cp35.cp36.cp37-abi3-linux_x86_64.whl
